### PR TITLE
Fix error "max priority fee per gas higher than max fee per gas", Change maxPriorityFeePerGas

### PR DESCRIPTION
**Pull request by mylastwanto**
Change maxPriorityFeePerGas to BigInteger.valueOf(50000000L), default is BigInteger.valueOf(100000000L) will get an error from node. max priority fee per gas higher than max fee per gas

### CODE REVIEW

**Comment by petarTxFusion** [comment]
Could you please share how to reproduce this issue?

**Comment by petarTxFusion** [comment]
LGTM! There is an issue with Test job and check code format. I will resolve that and if you can fix: check commits from forks

**Comment by mylastwanto** [comment]
Done :)

**Comment by petarTxFusion** [comment]
We have decided to convert this to be optional so I will close this PR. Thank for finding a bug and contributing

**Pull request closed without merging**
